### ISSUE TITLE
StreamSocketClient throws exception

### ISSUE THREAD

**Issue by povils** [bzikarsky/gelf-php#67]
Does it make sense that StreamSocketClient::buildSocket method throws exception if it can't connect? I mean if graylog server is down, nobody is catching this exception and my app is no available.  Or one of solution would be instead of RuntimeException throw more specific exception that i could catch and handle it.

**Comment by bzikarsky** [comment]
An exception should be logged to the local error log. If there is a systemic problem (such as no network connectivity) this is IMO the right place look up any errors.

**Comment by chrisnew** [comment]
I ran into the same issue today and it’s definitely not a reasonable option to let a whole application just crash in case if there’s a Log::debug() call failing and throwing some exceptions, because the graylog server is not responding on time due to some bad Internet weather… ;)

**Comment by bzikarsky** [comment]
Hm. That is a valid point of view 😃, looks like I was a little hasty with closing this issue -- What do you propose?

I think it's fine for the StreamSocketClient to throw an exception if it fails. But the wrapping transport object could allow for a "failure-resistent" mode. We already have https://github.com/bzikarsky/gelf-php/blob/master/src/Gelf/Transport/IgnoreErrorTransportWrapper.php for handling errors during `send()`. 
It does not work yet, because I assume the error occurs during object-construction (when the StreamSocketClient-constructor is called). If we initialize the StreackSocketClient lazily (on-demand) , the exception would be triggered during `send()` and therefore caught by the IgnoreError-Wrapper.

**Comment by bzikarsky** [comment]
Damn, typo in commit-message

**Comment by bzikarsky** [comment]
I just did a quick check: None of the transports will throw an exception in constructor. They only setup their dependencies (pretty much only the MessageEncoder and possibly a StreamSocketClient). But even those don't throw exceptions in their constructor. 

This leads me to the conclusion that you should be able to solve your problem by wrapping your Udp/Tcp/Http/...-Transport in the `IgnoreErrorTransportWrapper`.

Is this an acceptable solution?

**Comment by bzikarsky** [comment]
ping @povils and @chrisnew 😃

**Comment by chrisnew** [comment]
Sorry, got some busy weeks lately. ;) I’ll check tonight!

**Comment by florianbrinkmann** [comment]
I have the same issue in a Laravel project where I use http as transport and got the following exception from a `Log::debug()` call:

```
RuntimeException: Graylog-Server didn't answer properly, expected 'HTTP/1.x 202 Accepted', response is '' in /vendor/graylog2/gelf-php/src/Gelf/Transport/HttpTransport.php:227
```

**Comment by bzikarsky** [comment]
If it's due to long-running, kept-alive HTTP sockets, this may also be related https://github.com/bzikarsky/gelf-php/pull/128 (It's the fix from the newest gelf-php version, but also references a possibly related issue)

**Comment by florianbrinkmann** [comment]
Thanks for the hint!
